//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_AuditionDate_Musical", "Musical", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.Musical), "AuditionDate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.AuditionDate), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_AuditionTime_AuditionDate", "AuditionDate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.AuditionDate), "AuditionTime", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.AuditionTime), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_StudentTime_AuditionTime", "AuditionTime", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.AuditionTime), "StudentTime", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.StudentTime), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_MusicalRole_Musical", "Musical", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.Musical), "MusicalRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.MusicalRole), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_Student_Musical", "Musical", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.Musical), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.Student), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_StudentRole_MusicalRole", "MusicalRole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.MusicalRole), "StudentRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.StudentRole), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_Student_StudentCode", "StudentCode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.StudentCode), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.Student), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_StudentRole_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.Student), "StudentRole", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.StudentRole), true)]
[assembly: EdmRelationshipAttribute("BayviewMusical", "FK_StudentTime_Student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BayviewMusical.Student), "StudentTime", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BayviewMusical.StudentTime), true)]

#endregion

namespace BayviewMusical
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BayviewMusicalContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BayviewMusicalContext object using the connection string found in the 'BayviewMusicalContext' section of the application configuration file.
        /// </summary>
        public BayviewMusicalContext() : base("name=BayviewMusicalContext", "BayviewMusicalContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BayviewMusicalContext object.
        /// </summary>
        public BayviewMusicalContext(string connectionString) : base(connectionString, "BayviewMusicalContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BayviewMusicalContext object.
        /// </summary>
        public BayviewMusicalContext(EntityConnection connection) : base(connection, "BayviewMusicalContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditionDate> AuditionDates
        {
            get
            {
                if ((_AuditionDates == null))
                {
                    _AuditionDates = base.CreateObjectSet<AuditionDate>("AuditionDates");
                }
                return _AuditionDates;
            }
        }
        private ObjectSet<AuditionDate> _AuditionDates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditionTime> AuditionTimes
        {
            get
            {
                if ((_AuditionTimes == null))
                {
                    _AuditionTimes = base.CreateObjectSet<AuditionTime>("AuditionTimes");
                }
                return _AuditionTimes;
            }
        }
        private ObjectSet<AuditionTime> _AuditionTimes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Musical> Musicals
        {
            get
            {
                if ((_Musicals == null))
                {
                    _Musicals = base.CreateObjectSet<Musical>("Musicals");
                }
                return _Musicals;
            }
        }
        private ObjectSet<Musical> _Musicals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MusicalRole> MusicalRoles
        {
            get
            {
                if ((_MusicalRoles == null))
                {
                    _MusicalRoles = base.CreateObjectSet<MusicalRole>("MusicalRoles");
                }
                return _MusicalRoles;
            }
        }
        private ObjectSet<MusicalRole> _MusicalRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentCode> StudentCodes
        {
            get
            {
                if ((_StudentCodes == null))
                {
                    _StudentCodes = base.CreateObjectSet<StudentCode>("StudentCodes");
                }
                return _StudentCodes;
            }
        }
        private ObjectSet<StudentCode> _StudentCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentRole> StudentRoles
        {
            get
            {
                if ((_StudentRoles == null))
                {
                    _StudentRoles = base.CreateObjectSet<StudentRole>("StudentRoles");
                }
                return _StudentRoles;
            }
        }
        private ObjectSet<StudentRole> _StudentRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentTime> StudentTimes
        {
            get
            {
                if ((_StudentTimes == null))
                {
                    _StudentTimes = base.CreateObjectSet<StudentTime>("StudentTimes");
                }
                return _StudentTimes;
            }
        }
        private ObjectSet<StudentTime> _StudentTimes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Account> Accounts
        {
            get
            {
                if ((_Accounts == null))
                {
                    _Accounts = base.CreateObjectSet<Account>("Accounts");
                }
                return _Accounts;
            }
        }
        private ObjectSet<Account> _Accounts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditionDates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditionDates(AuditionDate auditionDate)
        {
            base.AddObject("AuditionDates", auditionDate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditionTimes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditionTimes(AuditionTime auditionTime)
        {
            base.AddObject("AuditionTimes", auditionTime);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Musicals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMusicals(Musical musical)
        {
            base.AddObject("Musicals", musical);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MusicalRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMusicalRoles(MusicalRole musicalRole)
        {
            base.AddObject("MusicalRoles", musicalRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentCodes(StudentCode studentCode)
        {
            base.AddObject("StudentCodes", studentCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentRoles(StudentRole studentRole)
        {
            base.AddObject("StudentRoles", studentRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentTimes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentTimes(StudentTime studentTime)
        {
            base.AddObject("StudentTimes", studentTime);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccounts(Account account)
        {
            base.AddObject("Accounts", account);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="accountID">Initial value of the AccountID property.</param>
        public static Account CreateAccount(global::System.Int32 accountID)
        {
            Account account = new Account();
            account.AccountID = accountID;
            return account;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountID
        {
            get
            {
                return _AccountID;
            }
            set
            {
                if (_AccountID != value)
                {
                    OnAccountIDChanging(value);
                    ReportPropertyChanging("AccountID");
                    _AccountID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountID");
                    OnAccountIDChanged();
                }
            }
        }
        private global::System.Int32 _AccountID;
        partial void OnAccountIDChanging(global::System.Int32 value);
        partial void OnAccountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="AuditionDate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditionDate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditionDate object.
        /// </summary>
        /// <param name="dateID">Initial value of the dateID property.</param>
        /// <param name="musicalID">Initial value of the musicalID property.</param>
        public static AuditionDate CreateAuditionDate(global::System.Int32 dateID, global::System.Int32 musicalID)
        {
            AuditionDate auditionDate = new AuditionDate();
            auditionDate.dateID = dateID;
            auditionDate.musicalID = musicalID;
            return auditionDate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dateID
        {
            get
            {
                return _dateID;
            }
            set
            {
                if (_dateID != value)
                {
                    OndateIDChanging(value);
                    ReportPropertyChanging("dateID");
                    _dateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dateID");
                    OndateIDChanged();
                }
            }
        }
        private global::System.Int32 _dateID;
        partial void OndateIDChanging(global::System.Int32 value);
        partial void OndateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 musicalID
        {
            get
            {
                return _musicalID;
            }
            set
            {
                OnmusicalIDChanging(value);
                ReportPropertyChanging("musicalID");
                _musicalID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("musicalID");
                OnmusicalIDChanged();
            }
        }
        private global::System.Int32 _musicalID;
        partial void OnmusicalIDChanging(global::System.Int32 value);
        partial void OnmusicalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_AuditionDate_Musical", "Musical")]
        public Musical Musical
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_AuditionDate_Musical", "Musical").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_AuditionDate_Musical", "Musical").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Musical> MusicalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_AuditionDate_Musical", "Musical");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Musical>("BayviewMusical.FK_AuditionDate_Musical", "Musical", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_AuditionTime_AuditionDate", "AuditionTime")]
        public EntityCollection<AuditionTime> AuditionTimes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditionTime>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditionTime>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionTime", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="AuditionTime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditionTime : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditionTime object.
        /// </summary>
        /// <param name="timeID">Initial value of the timeID property.</param>
        /// <param name="dateID">Initial value of the dateID property.</param>
        public static AuditionTime CreateAuditionTime(global::System.Int32 timeID, global::System.Int32 dateID)
        {
            AuditionTime auditionTime = new AuditionTime();
            auditionTime.timeID = timeID;
            auditionTime.dateID = dateID;
            return auditionTime;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 timeID
        {
            get
            {
                return _timeID;
            }
            set
            {
                if (_timeID != value)
                {
                    OntimeIDChanging(value);
                    ReportPropertyChanging("timeID");
                    _timeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("timeID");
                    OntimeIDChanged();
                }
            }
        }
        private global::System.Int32 _timeID;
        partial void OntimeIDChanging(global::System.Int32 value);
        partial void OntimeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dateID
        {
            get
            {
                return _dateID;
            }
            set
            {
                OndateIDChanging(value);
                ReportPropertyChanging("dateID");
                _dateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateID");
                OndateIDChanged();
            }
        }
        private global::System.Int32 _dateID;
        partial void OndateIDChanging(global::System.Int32 value);
        partial void OndateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String timeDescription
        {
            get
            {
                return _timeDescription;
            }
            set
            {
                OntimeDescriptionChanging(value);
                ReportPropertyChanging("timeDescription");
                _timeDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("timeDescription");
                OntimeDescriptionChanged();
            }
        }
        private global::System.String _timeDescription;
        partial void OntimeDescriptionChanging(global::System.String value);
        partial void OntimeDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> availableSlots
        {
            get
            {
                return _availableSlots;
            }
            set
            {
                OnavailableSlotsChanging(value);
                ReportPropertyChanging("availableSlots");
                _availableSlots = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("availableSlots");
                OnavailableSlotsChanged();
            }
        }
        private Nullable<global::System.Int32> _availableSlots;
        partial void OnavailableSlotsChanging(Nullable<global::System.Int32> value);
        partial void OnavailableSlotsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> signupStartDate
        {
            get
            {
                return _signupStartDate;
            }
            set
            {
                OnsignupStartDateChanging(value);
                ReportPropertyChanging("signupStartDate");
                _signupStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signupStartDate");
                OnsignupStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _signupStartDate;
        partial void OnsignupStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnsignupStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> signupEndDate
        {
            get
            {
                return _signupEndDate;
            }
            set
            {
                OnsignupEndDateChanging(value);
                ReportPropertyChanging("signupEndDate");
                _signupEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signupEndDate");
                OnsignupEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _signupEndDate;
        partial void OnsignupEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnsignupEndDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_AuditionTime_AuditionDate", "AuditionDate")]
        public AuditionDate AuditionDate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionDate>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionDate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionDate>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionDate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AuditionDate> AuditionDateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionDate>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionDate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AuditionDate>("BayviewMusical.FK_AuditionTime_AuditionDate", "AuditionDate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentTime_AuditionTime", "StudentTime")]
        public EntityCollection<StudentTime> StudentTimes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentTime>("BayviewMusical.FK_StudentTime_AuditionTime", "StudentTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentTime>("BayviewMusical.FK_StudentTime_AuditionTime", "StudentTime", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="Musical")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Musical : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Musical object.
        /// </summary>
        /// <param name="musicalID">Initial value of the musicalID property.</param>
        public static Musical CreateMusical(global::System.Int32 musicalID)
        {
            Musical musical = new Musical();
            musical.musicalID = musicalID;
            return musical;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 musicalID
        {
            get
            {
                return _musicalID;
            }
            set
            {
                if (_musicalID != value)
                {
                    OnmusicalIDChanging(value);
                    ReportPropertyChanging("musicalID");
                    _musicalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("musicalID");
                    OnmusicalIDChanged();
                }
            }
        }
        private global::System.Int32 _musicalID;
        partial void OnmusicalIDChanging(global::System.Int32 value);
        partial void OnmusicalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> signupStartDate
        {
            get
            {
                return _signupStartDate;
            }
            set
            {
                OnsignupStartDateChanging(value);
                ReportPropertyChanging("signupStartDate");
                _signupStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signupStartDate");
                OnsignupStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _signupStartDate;
        partial void OnsignupStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnsignupStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> signupEndDate
        {
            get
            {
                return _signupEndDate;
            }
            set
            {
                OnsignupEndDateChanging(value);
                ReportPropertyChanging("signupEndDate");
                _signupEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("signupEndDate");
                OnsignupEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _signupEndDate;
        partial void OnsignupEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnsignupEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String expiredMessage
        {
            get
            {
                return _expiredMessage;
            }
            set
            {
                OnexpiredMessageChanging(value);
                ReportPropertyChanging("expiredMessage");
                _expiredMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("expiredMessage");
                OnexpiredMessageChanged();
            }
        }
        private global::System.String _expiredMessage;
        partial void OnexpiredMessageChanging(global::System.String value);
        partial void OnexpiredMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String confirmationMessage
        {
            get
            {
                return _confirmationMessage;
            }
            set
            {
                OnconfirmationMessageChanging(value);
                ReportPropertyChanging("confirmationMessage");
                _confirmationMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("confirmationMessage");
                OnconfirmationMessageChanged();
            }
        }
        private global::System.String _confirmationMessage;
        partial void OnconfirmationMessageChanging(global::System.String value);
        partial void OnconfirmationMessageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_AuditionDate_Musical", "AuditionDate")]
        public EntityCollection<AuditionDate> AuditionDates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AuditionDate>("BayviewMusical.FK_AuditionDate_Musical", "AuditionDate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AuditionDate>("BayviewMusical.FK_AuditionDate_Musical", "AuditionDate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_MusicalRole_Musical", "MusicalRole")]
        public EntityCollection<MusicalRole> MusicalRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MusicalRole>("BayviewMusical.FK_MusicalRole_Musical", "MusicalRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MusicalRole>("BayviewMusical.FK_MusicalRole_Musical", "MusicalRole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_Student_Musical", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("BayviewMusical.FK_Student_Musical", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("BayviewMusical.FK_Student_Musical", "Student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="MusicalRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MusicalRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MusicalRole object.
        /// </summary>
        /// <param name="roleID">Initial value of the roleID property.</param>
        /// <param name="musicalID">Initial value of the musicalID property.</param>
        public static MusicalRole CreateMusicalRole(global::System.Int32 roleID, global::System.Int32 musicalID)
        {
            MusicalRole musicalRole = new MusicalRole();
            musicalRole.roleID = roleID;
            musicalRole.musicalID = musicalID;
            return musicalRole;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleID
        {
            get
            {
                return _roleID;
            }
            set
            {
                if (_roleID != value)
                {
                    OnroleIDChanging(value);
                    ReportPropertyChanging("roleID");
                    _roleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("roleID");
                    OnroleIDChanged();
                }
            }
        }
        private global::System.Int32 _roleID;
        partial void OnroleIDChanging(global::System.Int32 value);
        partial void OnroleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 musicalID
        {
            get
            {
                return _musicalID;
            }
            set
            {
                OnmusicalIDChanging(value);
                ReportPropertyChanging("musicalID");
                _musicalID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("musicalID");
                OnmusicalIDChanged();
            }
        }
        private global::System.Int32 _musicalID;
        partial void OnmusicalIDChanging(global::System.Int32 value);
        partial void OnmusicalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private global::System.String _grade;
        partial void OngradeChanging(global::System.String value);
        partial void OngradeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_MusicalRole_Musical", "Musical")]
        public Musical Musical
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_MusicalRole_Musical", "Musical").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_MusicalRole_Musical", "Musical").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Musical> MusicalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_MusicalRole_Musical", "Musical");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Musical>("BayviewMusical.FK_MusicalRole_Musical", "Musical", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentRole_MusicalRole", "StudentRole")]
        public EntityCollection<StudentRole> StudentRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentRole>("BayviewMusical.FK_StudentRole_MusicalRole", "StudentRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentRole>("BayviewMusical.FK_StudentRole_MusicalRole", "StudentRole", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="studentID">Initial value of the studentID property.</param>
        /// <param name="code">Initial value of the code property.</param>
        /// <param name="musicalID">Initial value of the musicalID property.</param>
        public static Student CreateStudent(global::System.Int32 studentID, global::System.String code, global::System.Int32 musicalID)
        {
            Student student = new Student();
            student.studentID = studentID;
            student.code = code;
            student.musicalID = musicalID;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentID
        {
            get
            {
                return _studentID;
            }
            set
            {
                if (_studentID != value)
                {
                    OnstudentIDChanging(value);
                    ReportPropertyChanging("studentID");
                    _studentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studentID");
                    OnstudentIDChanged();
                }
            }
        }
        private global::System.Int32 _studentID;
        partial void OnstudentIDChanging(global::System.Int32 value);
        partial void OnstudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 musicalID
        {
            get
            {
                return _musicalID;
            }
            set
            {
                OnmusicalIDChanging(value);
                ReportPropertyChanging("musicalID");
                _musicalID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("musicalID");
                OnmusicalIDChanged();
            }
        }
        private global::System.Int32 _musicalID;
        partial void OnmusicalIDChanging(global::System.Int32 value);
        partial void OnmusicalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private global::System.String _grade;
        partial void OngradeChanging(global::System.String value);
        partial void OngradeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_Student_Musical", "Musical")]
        public Musical Musical
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_Student_Musical", "Musical").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_Student_Musical", "Musical").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Musical> MusicalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musical>("BayviewMusical.FK_Student_Musical", "Musical");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Musical>("BayviewMusical.FK_Student_Musical", "Musical", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_Student_StudentCode", "StudentCode")]
        public StudentCode StudentCode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentCode>("BayviewMusical.FK_Student_StudentCode", "StudentCode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentCode>("BayviewMusical.FK_Student_StudentCode", "StudentCode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentCode> StudentCodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentCode>("BayviewMusical.FK_Student_StudentCode", "StudentCode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentCode>("BayviewMusical.FK_Student_StudentCode", "StudentCode", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentRole_Student", "StudentRole")]
        public EntityCollection<StudentRole> StudentRoles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentRole>("BayviewMusical.FK_StudentRole_Student", "StudentRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentRole>("BayviewMusical.FK_StudentRole_Student", "StudentRole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentTime_Student", "StudentTime")]
        public EntityCollection<StudentTime> StudentTimes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentTime>("BayviewMusical.FK_StudentTime_Student", "StudentTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentTime>("BayviewMusical.FK_StudentTime_Student", "StudentTime", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="StudentCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentCode object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static StudentCode CreateStudentCode(global::System.String code)
        {
            StudentCode studentCode = new StudentCode();
            studentCode.Code = code;
            return studentCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_Student_StudentCode", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("BayviewMusical.FK_Student_StudentCode", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("BayviewMusical.FK_Student_StudentCode", "Student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="StudentRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentRole object.
        /// </summary>
        /// <param name="studentRoleID">Initial value of the studentRoleID property.</param>
        /// <param name="roleID">Initial value of the roleID property.</param>
        /// <param name="studentID">Initial value of the studentID property.</param>
        public static StudentRole CreateStudentRole(global::System.Int32 studentRoleID, global::System.Int32 roleID, global::System.Int32 studentID)
        {
            StudentRole studentRole = new StudentRole();
            studentRole.studentRoleID = studentRoleID;
            studentRole.roleID = roleID;
            studentRole.studentID = studentID;
            return studentRole;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentRoleID
        {
            get
            {
                return _studentRoleID;
            }
            set
            {
                if (_studentRoleID != value)
                {
                    OnstudentRoleIDChanging(value);
                    ReportPropertyChanging("studentRoleID");
                    _studentRoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studentRoleID");
                    OnstudentRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _studentRoleID;
        partial void OnstudentRoleIDChanging(global::System.Int32 value);
        partial void OnstudentRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 roleID
        {
            get
            {
                return _roleID;
            }
            set
            {
                OnroleIDChanging(value);
                ReportPropertyChanging("roleID");
                _roleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleID");
                OnroleIDChanged();
            }
        }
        private global::System.Int32 _roleID;
        partial void OnroleIDChanging(global::System.Int32 value);
        partial void OnroleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentID
        {
            get
            {
                return _studentID;
            }
            set
            {
                OnstudentIDChanging(value);
                ReportPropertyChanging("studentID");
                _studentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studentID");
                OnstudentIDChanged();
            }
        }
        private global::System.Int32 _studentID;
        partial void OnstudentIDChanging(global::System.Int32 value);
        partial void OnstudentIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentRole_MusicalRole", "MusicalRole")]
        public MusicalRole MusicalRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MusicalRole>("BayviewMusical.FK_StudentRole_MusicalRole", "MusicalRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MusicalRole>("BayviewMusical.FK_StudentRole_MusicalRole", "MusicalRole").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MusicalRole> MusicalRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MusicalRole>("BayviewMusical.FK_StudentRole_MusicalRole", "MusicalRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MusicalRole>("BayviewMusical.FK_StudentRole_MusicalRole", "MusicalRole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentRole_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentRole_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentRole_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentRole_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("BayviewMusical.FK_StudentRole_Student", "Student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BayviewMusical", Name="StudentTime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentTime : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentTime object.
        /// </summary>
        /// <param name="studentTimeID">Initial value of the studentTimeID property.</param>
        /// <param name="studentID">Initial value of the studentID property.</param>
        /// <param name="timeID">Initial value of the timeID property.</param>
        public static StudentTime CreateStudentTime(global::System.Int32 studentTimeID, global::System.Int32 studentID, global::System.Int32 timeID)
        {
            StudentTime studentTime = new StudentTime();
            studentTime.studentTimeID = studentTimeID;
            studentTime.studentID = studentID;
            studentTime.timeID = timeID;
            return studentTime;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentTimeID
        {
            get
            {
                return _studentTimeID;
            }
            set
            {
                if (_studentTimeID != value)
                {
                    OnstudentTimeIDChanging(value);
                    ReportPropertyChanging("studentTimeID");
                    _studentTimeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("studentTimeID");
                    OnstudentTimeIDChanged();
                }
            }
        }
        private global::System.Int32 _studentTimeID;
        partial void OnstudentTimeIDChanging(global::System.Int32 value);
        partial void OnstudentTimeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentID
        {
            get
            {
                return _studentID;
            }
            set
            {
                OnstudentIDChanging(value);
                ReportPropertyChanging("studentID");
                _studentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studentID");
                OnstudentIDChanged();
            }
        }
        private global::System.Int32 _studentID;
        partial void OnstudentIDChanging(global::System.Int32 value);
        partial void OnstudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 timeID
        {
            get
            {
                return _timeID;
            }
            set
            {
                OntimeIDChanging(value);
                ReportPropertyChanging("timeID");
                _timeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timeID");
                OntimeIDChanged();
            }
        }
        private global::System.Int32 _timeID;
        partial void OntimeIDChanging(global::System.Int32 value);
        partial void OntimeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentTime_AuditionTime", "AuditionTime")]
        public AuditionTime AuditionTime
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionTime>("BayviewMusical.FK_StudentTime_AuditionTime", "AuditionTime").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionTime>("BayviewMusical.FK_StudentTime_AuditionTime", "AuditionTime").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AuditionTime> AuditionTimeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AuditionTime>("BayviewMusical.FK_StudentTime_AuditionTime", "AuditionTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AuditionTime>("BayviewMusical.FK_StudentTime_AuditionTime", "AuditionTime", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BayviewMusical", "FK_StudentTime_Student", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentTime_Student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentTime_Student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BayviewMusical.FK_StudentTime_Student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("BayviewMusical.FK_StudentTime_Student", "Student", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
